config {
    type: "view",
    materialized: true,
    database: "trip-record-data",
    schema: "BI_dashboards",
    name: "peak_hours",
    tags: ["peaks"]

}


SELECT 
pickup_hour,
pd.is_weekend AS pickup_is_weekend,
--dropoff data
droppoff_hour,
dd.is_weekend AS dropoff_is_weekend,
COUNT(DISTINCT trip_id) AS trip_count

FROM  ${ref("fact_trip_data")} f
LEFT JOIN ${ref("dim_date")} pd
ON f.pickup_date = pd.date
LEFT JOIN ${ref("dim_date")} dd
ON f.dropoff_date = dd.date
GROUP BY 1,2,3,4