config {
    type: "view",
    materialized: true,
    database: "trip-record-data",
    schema: "BI_dashboards",
    name: "peak_zones",
    tags: ["peaks"]

}

SELECT
  puz.Borough AS pickup_Borough,
  puz.Zone AS pickup_Zone,
  puz.service_zone AS pickup_service_zone,
  ANY_VALUE(puz.zone_geog) AS pickup_zone_geog,
  pickup_date,
  pd.is_weekend AS pickup_is_weekend,
  --dropoff data
  drz.Borough AS dropoff_Borough,
  drz.Zone AS dropoff_Zone,
  drz.service_zone AS dropoff_service_zone,
  ANY_VALUE(drz.zone_geog) AS dropoff_zone_geog,
  dropoff_date,
  dd.is_weekend AS dropoff_is_weekend,
  COUNT(f.trip_id)AS trip_count
FROM
  ${ref("fact_trip_data")} f
LEFT JOIN
  ${ref("dim_zones")} puz
ON
  f.PULocationID = puz.LocationID
LEFT JOIN
  ${ref("dim_zones")} drz
ON
  f.DOLocationID = drz.LocationID
LEFT JOIN
  ${ref("dim_date")} pd
ON
  f.pickup_date = pd.date
LEFT JOIN
  ${ref("dim_date")} dd
ON
  f.dropoff_date = dd.date
GROUP BY
  pickup_Borough,
  pickup_Zone,
  pickup_service_zone,
  pickup_date,
  pickup_is_weekend,
  dropoff_Borough,
  dropoff_Zone,
  dropoff_service_zone,
  dropoff_date,
  dropoff_is_weekend
