    config {
      type: "operations",
      hasOutput: true,
      database: "trip-record-data",
      schema: "load_staging_layer",
      name: "yellow_tripdata",
      
        description: "This table is desgined full refresh for ingesting raw data from different buckets from GCS.",
      columns: {
        VendorID: "A code indicating the TPEP provider that provided the record. 1 = Creative Mobile Technologies, LLC 2 = Curb Mobility, LLC 6 = Myle Technologies Inc 7 = Helix",
        tpep_pickup_datetime: "The date and time when the meter was engaged.",
        tpep_dropoff_datetime: "The date and time when the meter was disengaged.",
        passenger_count: "The number of passengers in the vehicle.",
        trip_distance: "The elapsed trip distance in miles reported by the taximeter.",
        RatecodeID: "The final rate code in effect at the end of the trip.",
        store_and_fwd_flag: "This flag indicates whether the trip record was held in vehicle memory before sending to the vendor, aka “store and forward,” because the vehicle did not have a connection to the server. Y = store and forward trip N = not a store and forward trip",
        PULocationID: "TLC Taxi Zone in which the taximeter was engaged",
        DOLocationID: "TLC Taxi Zone in which the taximeter was disengaged.",
        payment_type: "A numeric code signifying how the passenger paid for the trip.",
        fare_amount: "The time-and-distance fare calculated by the meter.",
        extra: "Miscellaneous extras and surcharges.",
        mta_tax: "Tax that is automatically triggered based on the metered rate in use.",
        tip_amount: "Tip amount This field is automatically populated for credit card tips. Cash tips are not included.",
        tolls_amount: "Total amount of all tolls paid in trip",
        improvement_surcharge: "Improvement surcharge assessed trips at the flag drop. The improvement surcharge began being levied in 2015.",
        total_amount: "The total amount charged to passengers. Does not include cash tips.",
        congestion_surcharge: "Total amount collected in trip for NYS congestion surcharge.",
        Airport_fee: "For pick up only at LaGuardia and John F. Kennedy Airports.",
        cbd_congestion_fee: "Per-trip charge for MTA's Congestion Relief Zone starting Jan. 5, 2025."

        }
    }


    LOAD DATA OVERWRITE ${self()} (

          VendorID		INTEGER,
          tpep_pickup_datetime		TIMESTAMP	,
          tpep_dropoff_datetime		TIMESTAMP	,
          passenger_count		INTEGER	,
          trip_distance		FLOAT64	,
          RatecodeID		INTEGER	,
          store_and_fwd_flag		STRING	,
          PULocationID		INTEGER	,
          DOLocationID		INTEGER	,
          payment_type		INTEGER	,
          fare_amount		FLOAT64	,
          extra		FLOAT64	,
          mta_tax		FLOAT64	,
          tip_amount		FLOAT64	,
          tolls_amount		FLOAT64	,
          improvement_surcharge		FLOAT64	,
          total_amount		FLOAT64	,
          congestion_surcharge		FLOAT64	,
          Airport_fee		FLOAT64	,
          cbd_congestion_fee		FLOAT64
          )
          FROM FILES (
  format = 'PARQUET',
  uris = ['gs://trip_record_data/yellow_tripdata_*.parquet']);


 
