config {
    type: "operations",
    hasOutput: true,
    database: "trip-record-data",
    schema: "load_staging_layer",
    name: "taxi_zones",
    description: "This table is a dimension for Taxi zones  ",
    columns: {
        LocationID: "Identifier of the location",
        Borough: "Borough of the trip started or ended",
        Zone: " Zone where the trip was started or ended",
        service_zone: "Service zone of the related Taxi",

    }
}

LOAD DATA OVERWRITE
  ${self()} ( LocationID INT64,
    Borough STRING,
    Zone STRING,
    service_zone STRING )
FROM FILES ( format = 'CSV',
    quote = '"',
    field_delimiter=',',
    allow_quoted_newlines = TRUE,
    skip_leading_rows = 1,
    encoding = 'ISO-8859-1',
    max_bad_records = 0,
    uris = ['gs://trip_record_data/taxi_zone_lookup.csv']);
